#include<iostream>
using namespace std;

int main(){



    // for(int i=1; i<= 10; i=i+1)
    // {
    //     cout << i << endl;
    // }



    // for(int i=1; i<= 10; i=i+1)
    // {
    //     cout << "Apple" << endl;
    // }


    // // counting form 51 to 69;

    // for(int i=51; i<= 69; i=i+1)
    // {
    //     cout << i << endl;
    // }



    
    // for(int i=1; i<= 10; i=i+1)
    // {
    //     cout << i << " ";
    // }



    // for(int i=1; i<= 10; i=i+1)
    // {
    //     cout << i << " ";
    //     if(i==5){
    //         break;
    //     }
    // }
    

    // cout << endl;

    //     for(int i=1; i<= 10; i=i+1)
    // { 
    //     if(i==5){
    //         break;
    //     }
    //     cout << i << " ";
    // }









    //     cout << endl;

    //     for(int i=1; i<= 10; i=i+1)
    // { 
    //     if(i==5){
    //         continue;
    //     }
    //     cout << i << " ";
    // }

    // cout << " here 5 is missing";




    int i=1;
    while(i<=5){
        cout << i << " ";
        i=i+1;

    }






 
    




    return 0;
}
